### PR TITLE
Update uglify to v2.7.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @shama @vladikoff for thoughts and new version number suggestion.

### CODE REVIEW

**Comment by avdg** [comment]
Uh not sure how to get these ie8 tests fixed. If they don't test the output for being ie8 friendly then they aren't needed. But those tests will be removed on long term anyway.

**Comment by XhmikosR** [comment]
Huh???? They are tested just fine.

**Comment by avdg** [comment]
Uh.., I just saw theses tests being modified. I might have been too worried. I didn't had time to look deeper into it yet.

**Comment by avdg** [comment]
Ah yeah, the test is just doing the opposite after it and testing when screwIE8 is enabled instead of disabled. Edgy but fine I guess since these tests will be removed long term anyway...

**Comment by vladikoff** [comment]
AppVeyor says "good". let Travis check `master`

**Pull request merged**
