### PR TITLE
v1.0.2.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @vladikoff 

`git tag` and `npm publish` after this is merged. Then we can merge the remaining PRs and bump to v2.0.0.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Will you tag and npm publish @vladikoff?

Also, please publish grunt-contrib-internal since I don't have npm rights.

**Comment by vladikoff** [comment]
@XhmikosR gave you npm rights to this uglify plugin

**Comment by vladikoff** [comment]
@XhmikosR published internal!

**Comment by XhmikosR** [comment]
Thanks!

**Pull request merged**
