### PR TITLE
Update uglify

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @ @alexlamsl: are there any breaking changes in 2.8.0 we should take care of? So far I see Windows builds fail due to `WARN: Output exceeds 40 characters`.

### CODE REVIEW

**Comment by alexlamsl** [comment]
@XhmikosR that warning is new but harmless - it merely states the fact that the despite specifying `output = {max_line_len: 40}` it was unable to quite fit the line into that stated limit.

I guess a test in this project has set that specifically.

**Comment by XhmikosR** [comment]
I'll see how to work around this then.

Are there any breaking changes though?

**Comment by alexlamsl** [comment]
`global_defs` now applies to [globally declared variables](https://github.com/mishoo/UglifyJS2/pull/1469#issuecomment-278231528) - but this option does nothing by default.

Not sure if these counts as well, but `collapse_vars` and `reduce_vars` are now enabled by default.

**Comment by XhmikosR** [comment]
OK, thanks. Those shouldn't affect us.

**Comment by alexlamsl** [comment]
@XhmikosR please consider applying the one-liner from https://github.com/mishoo/UglifyJS2/issues/1516#issuecomment-283102405

**Comment by XhmikosR** [comment]
@alexlamsl; you mean in this branch? Note that I have no idea why they say there they get 2.8.0 since we use a tilde for uglify so it shouldn't get that.

**Comment by alexlamsl** [comment]
@XhmikosR I mumbled about that in https://github.com/mishoo/UglifyJS2/pull/1519#issuecomment-283120363 as well.

Anyway, this new method is introduced back in `uglify-js 2.6.3`, and without it `passes` (& now `reduce_vars`) cannot be used, i.e. they will be no-op.

**Comment by XhmikosR** [comment]
@alexlamsl: so I apply that one line patch and I get different output. Is that normal?

I pushed the patches in this branch for you to have a quick look.

**Comment by alexlamsl** [comment]
@XhmikosR the minified `.js` looks correct to me (I don't have enough knowledge on source maps)

Thanks!

**Comment by XhmikosR** [comment]
I'm gonna merge this and release the new version in a few hours.

**Comment by kzc** [comment]
2.8.3 will be released shortly:

https://github.com/mishoo/UglifyJS2/pull/1523

**Comment by XhmikosR** [comment]
@kzc: although it shouldn't matter due to us using tilde for uglify version, I can wait for 2.8.3, rebase and then release the new version.

**Comment by kzc** [comment]
@XhmikosR True, but that `uglify-js@2.8.2` error is fairly likely to occur in the wild.

**Comment by alexlamsl** [comment]
`uglify 2.8.3` released.

**Pull request merged**
