### PR TITLE
Log fixes.

### PR DESCRIPTION
**Pull request by XhmikosR**
Now the output is similar to grunt-contrib-cssmin.

@vladikoff: I hope nothing broke along the way. This should be merged after we release a new version with the updated uglify.

### CODE REVIEW

**Comment by XhmikosR** [comment]
@vladikoff: any thoughts?

**Comment by XhmikosR** [comment]
@vladikoff: bump

**Comment by vladikoff** [comment]
tested locally, works well! Thanks!

**Comment by XhmikosR** [comment]
Should I release a patch version?

**Comment by vladikoff** [comment]
minor bump, not just patch. Thanks!

**Comment by XhmikosR** [comment]
Done, release 2.3.0.

**Pull request merged**
