### PR TITLE
Update UglifyJS to 3.13.3

### PR DESCRIPTION
**Pull request by paulschreiber**
Adds ES6 support.

### CODE REVIEW

**Comment by paulschreiber** [comment]
@vladikoff How do I sign the CLA? https://contribute.jquery.org/cla/ redirects to OpenJSF, with no obvious form to fill out.

**Comment by mgol** [comment]
@paulschreiber That redirect is wrong. Please click on the `Details` link next to the `license/cla` check that's pending; it will redirect you to the JSF CLA that needs to be signed.

**Comment by paulschreiber** [comment]
@vladikoff @mgol CLA was signed. Looks like some tests need updating.

**Comment by alexlamsl** [comment]
@paulschreiber I've updated the tests, and also brought the version forward to `v3.13.3` which has just been released.

**Comment by alexlamsl** [comment]
@vladikoff please publish `v5.0.1`

**Comment by vladikoff** [comment]
done!

**Pull request merged**
