### PR TITLE
upgrade to uglify-js 3.3.0

### PR DESCRIPTION
**Pull request by alexlamsl**
@XhmikosR let's try again - only included changes from `package.json` & `test/fixtures/expected/*`

Most changes are due to `hoist_funs` being disabled by default, as it seems to give worse uglified & gzip results on average.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Why don't you have the appveyor and travis changes? There is a reason they exist. 0.10 is ancient.

**Comment by alexlamsl** [comment]
@XhmikosR I wasn't sure what to include from the `grunt` task changes to the files, that's all :sweat: 

Done in https://github.com/gruntjs/grunt-contrib-uglify/pull/503/commits/06b13a4b634a287ca596a1aa0d9bdcbbfaa586a0

**Comment by alexlamsl** [comment]
Should I also include the auto-generated `README.md` changes here?

**Comment by XhmikosR** [comment]
@alexlamsl: don't merge yet please, I'll try to have a look later.

**Comment by alexlamsl** [comment]
@XhmikosR roger that - I shall leave this in your capable hands :wink: 

Thanks!

**Comment by XhmikosR** [comment]
All right, so I locked grunt-contrib-internal to 1.3.0 in order for us to keep 0.10.

If we want to drop that, we should do a major version bump, so I left it as it is for now.

**Comment by XhmikosR** [comment]
So, if the test file changes look good to you @alexlamsl we can merge it and tag/publish.

**Comment by alexlamsl** [comment]
@XhmikosR I've manually scanned and fixed all the tests, and they are good to go :+1:

**Comment by XhmikosR** [comment]
@alexlamsl: be careful when you rebase the harmony branch; you will need to update package-lock.json too there.

I just published 3.3.0.

**Comment by alexlamsl** [comment]
@XhmikosR thanks for the help – I shall be careful.

**Pull request merged**
