### PR TITLE
Reduce lodash usage

### PR DESCRIPTION
**Pull request by XhmikosR**
If/when we support >= 4 we can drop lodash.assign too.

/CC @vladikoff @shama

### CODE REVIEW

**Comment by avdg** [comment]
Uh yeah, I now see that Object.assign is actually es6 stuff (I was questioning that dependency). Version 4 is node version I assume.

We shouldn't do builds for node 5 and iojs anymore btw. At uglifyjs the builds are still enabled for 0.10 and 0.12, but I guess we better keep supporting it there as they don't have es 6 features and uglifyjs can work in the browser. Grunt-contrib-uglify doesn't have that problem.

So it should be fine to drop 0.10, iojs and 5 (unstable release, support ended) for now. Not sure if 0.12 has to be removed yet.

**Comment by XhmikosR** [comment]
@avdg: this is a big decision and the test scripts are maintained in grunt-contrib-internal. So make an issue there and CC shama, vladikoff and me.

**Comment by avdg** [comment]
I see, The main grunt base still support them. This should be decided on that level too.

**Comment by vladikoff** [comment]
AppVeyor says "good".

**Pull request merged**
