### PR TITLE
Fix screw ie8 option crash

### LINKED ISSUE #303: screwIE8 Option Causes Grunt to Abort
If I add the 'screwIE8: true' option I get the following error. When it is removed grunt runs fine.

````
$ grunt
Running "uglify:build" (uglify) task
Warning: Cannot assign to read only property 'screw_ie8' of true Use --force to continue.

Aborted due to warnings.
````

Version installed: grunt-contrib-uglify@0.8.0

### PR DESCRIPTION
**Pull request by avdg**
Just checking if the build fails because of this commit alone by merging with current master.

Should close #303 and #311 if there are no problems with the patch.

### CODE REVIEW

**Comment by vladikoff** [comment]
Seems to be good, @advg should we merge it?

**Comment by avdg** [comment]
I have no confirm of the fix on my part though the fix does look good on first sight, so I need a bit more time first

**Comment by avdg** [comment]
Ok, I can confirm that this patch solves the error message when options `screwIE8` and `mangle` are set to true.

LGTM

**Comment by avdg** [comment]
(yeah, I know I have merging rights, but I'm focussed on other projects)

@vladikoff Still planning to merge this?

**Comment by avdg** [comment]
Maybe I should add some tests first

**Pull request merged**
