### PR TITLE
Optionally set report verbosity level using report option

### PR DESCRIPTION
**Pull request by meschbach**
This pull request restores the documented behavior of generating the min/gzip reports at the standard log level while introducing the option to log the output to the verbose log using the values 'none' or false.  I believe this is a happy middle ground between between 4944e2c547858656af36098202022e22cb1fdbe2 and #254.

Resolves:
#254
#257 
#276 

Related To:
#259
#137 - changes from 4944e2c547858656af36098202022e22cb1fdbe2 look identical 
#229 - (Pull request)

### CODE REVIEW

**Comment by XhmikosR** [comment]
@meschbach: maybe add a test for `false`? Otherwise it seems to do the job fine :+1:

**Comment by meschbach** [comment]
Thank you for the feedback @XhmikosR !  Just to make sure we are on the same page, were you asking for a unit test to verify the verbose log would be utilized when the configuration value is false?

**Comment by XhmikosR** [comment]
@meschbach: yeah, exactly. You know, just to be safe.

/CC @sindresorhus @vladikoff

**Comment by sindresorhus** [comment]
:-1:

**Comment by XhmikosR** [comment]
What exactly is wrong with this approach @sindresorhus? Because what we have now is also wrong.

**Comment by meschbach** [comment]
@XhmikosR : There doesn't appear to be unit tests, however many system tests which I feel would be inappropriate for this particular test case; but if there is desire from a collaborator I would gladly add them.

@sindresorhus : I'm not really sure what to think of your feedback, however if there is something you do not like about the suggested patches I would gladly accept constructive criticism or a statement as why you are not interested in the patch set.

**Comment by tusbar** [comment]
:+1:

**Comment by sindresorhus** [comment]
@meschbach Exactly what it says, I don't think this is the right solution, but seeing as I don't have time to come up with a proper one, I'm willing to merge this if you fix the codestyle ;)

I also don't see the point in having both `false` and `'none'`.

**Comment by meschbach** [comment]
The commit eec87eb should bring the code style in-line with the remainder of the file.  I can respect desiring to find your own solution, however like you I am also busy.  I would be happy to make additional changes, but please be specific about what you would like to have changed. :-)

**Comment by vladikoff** [comment]
Thanks

**Pull request merged**
